#
# Glacier2 lib
#
include $(CLEAR_RULES)

LOCAL_MODULE	= IceBox
LOCAL_PATH	= cpp/src/$(LOCAL_MODULE)

LOCAL_SLICEDIR	= ice/slice/$(LOCAL_MODULE)
LOCAL_SLICES	= $(wildcard $(LOCAL_SLICEDIR)/*.ice)
LOCAL_SLICE2CPPFLAGS	= --ice -Iice/slice --dll-export ICE_BOX_API

LOCAL_SRCDIR	= ice/cpp/src/$(LOCAL_MODULE)
LOCAL_SRCS 	= $(LOCAL_SRCDIR)/Exception.cpp
LOCAL_CPPFLAGS	= -Icpp/src/$(LOCAL_MODULE)

include $(LIBRARY_RULES)

include $(CLEAR_RULES)
LOCAL_MODULE	= icebox
LOCAL_EXE	= $(LOCAL_MODULE)
LOCAL_PATH	= cpp/src/IceBox

LOCAL_LINK_WITH	= Ice IceBox
LOCAL_SRCDIR	= ice/$(LOCAL_PATH)
LOCAL_SRCS 	= $(LOCAL_SRCDIR)/Service.cpp \
		  $(LOCAL_SRCDIR)/ServiceManagerI.cpp
LOCAL_CPPFLAGS	= -I$(LOCAL_PATH)

include $(APPLICATION_RULES)

include $(CLEAR_RULES)
LOCAL_MODULE	= iceboxadmin
LOCAL_EXE	= $(LOCAL_MODULE)
LOCAL_PATH	= cpp/src/IceBox

LOCAL_LINK_WITH	= Ice IceBox
LOCAL_SRCDIR	= ice/$(LOCAL_PATH)
LOCAL_SRCS 	= $(LOCAL_SRCDIR)/Admin.cpp

LOCAL_CPPFLAGS	= -I$(LOCAL_PATH)

include $(APPLICATION_RULES)
